name: app-action-ci

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write
  security-events: write # Added for scans

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: orbitcluster/oc-cicd-dotnet-workflow@v1
        with:
          dotnet-version: "8.0.x"
          solution-path: "src/webApp"
          sonar-source-path: "src/webApp"
          test-directory: "test"
          app-name: "oc-dotnet-template"
          appid: "0"
          orgid: "0"
          buid: "0"
          role-to-assume: ${{ secrets.OC_ROLE_TO_ASSUME }}
