---
name: app-ci

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: orbitcluster/oc-cicd-dotnet-workflow@v1
        with:
          dotnet-version: "8.0.x"
          solution-path: "src/webApp"
          test-project-path: "test"

      - name: SAST Scan (CodeQL)
        uses: orbitcluster/oc-cicd-sast-workflow@feat/sast_init
        with:
          language: "csharp"
          build-mode: "manual"
          build-command: "dotnet build src/webApp --configuration Release"
