name: Release
on:
  push:
  pull_request:

jobs:
  semantic-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Version
        uses: orbitcluster/oc-cicd-release-workflow@main
        with:
          dry-run: ${{ github.ref_name != 'main' }}
          github-token: ${{ github.token }}

